joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: linearactuatorjoint   
  pid: {p: 1000, i: 0.0, d: 0.0}


  